name: deploy storybook on firebase and npm

# Run this workflow every time a new commit pushed on develop to update storybook and use it on other feature
on:
  release:
    types:
      - published

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests (automerge-action)
        # You may pin to the exact commit or the version.
        # uses: pascalgn/automerge-action@01fb84a9d077930bf9d16d1f7fa3fe2ffe45aabe
        uses: pascalgn/automerge-action@v0.14.2
        env:
          MERGE_LABELS: 'autorelease: pending'
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  build:
    needs: merge
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install libraries
        run: npm install
      - name: Build App
        run: npm run build-storybook
      - name: install firebase
        run: npm i firebase-tools -g
      - name: deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

  deploy-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
